# target_unigram:
#    decoder_type: transformer
#    dict: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/StreamSpeech/configs/fr-en/tgt_unigram3470/spm_unigram_fr.txt
#    data: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/StreamSpeech/configs/fr-en/tgt_unigram3470
#    loss_weight: 8.0
#    rdrop_alpha: 0.0
#    decoder_args:
#       decoder_layers: 4
#       decoder_embed_dim: 512
#       decoder_ffn_embed_dim: 2048
#       decoder_attention_heads: 8
#    label_smoothing: 0.1
# source_unigram:
#    decoder_type: ctc
#    dict: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/StreamSpeech/configs/fr-en/src_unigram3470/spm_unigram_fr.txt
#    data: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/StreamSpeech/configs/fr-en/src_unigram3470
#    loss_weight: 4.0
#    rdrop_alpha: 0.0
#    decoder_args:
#       decoder_layers: 0
#       decoder_embed_dim: 512
#       decoder_ffn_embed_dim: 2048
#       decoder_attention_heads: 8
#    label_smoothing: 0.1
# ctc_target_unigram:
#    decoder_type: ctc
#    dict: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/StreamSpeech/configs/fr-en/tgt_unigram3470/spm_unigram_fr.txt
#    data: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/StreamSpeech/configs/fr-en/tgt_unigram3470
#    loss_weight: 4.0
#    rdrop_alpha: 0.0
#    decoder_args:
#       decoder_layers: 0
#       decoder_embed_dim: 512
#       decoder_ffn_embed_dim: 2048
#       decoder_attention_heads: 8
#    label_smoothing: 0.1


target_unigram:
   decoder_type: transformer
   dict: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/datasets/cvss/cvss-c/fr-en/tgt_unigram6000/spm_unigram_fr.txt
   data: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/datasets/cvss/cvss-c/fr-en/tgt_unigram6000
   loss_weight: 8.0
   rdrop_alpha: 0.0
   decoder_args:
      decoder_layers: 4
      decoder_embed_dim: 512
      decoder_ffn_embed_dim: 2048
      decoder_attention_heads: 8
   label_smoothing: 0.1
source_unigram:
   decoder_type: ctc
   dict: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/datasets/cvss/cvss-c/fr-en/src_unigram6000/spm_unigram_fr.txt
   data: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/datasets/cvss/cvss-c/fr-en/src_unigram6000
   loss_weight: 4.0
   rdrop_alpha: 0.0
   decoder_args:
      decoder_layers: 0
      decoder_embed_dim: 512
      decoder_ffn_embed_dim: 2048
      decoder_attention_heads: 8
   label_smoothing: 0.1
ctc_target_unigram:
   decoder_type: ctc
   dict: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/datasets/cvss/cvss-c/fr-en/tgt_unigram6000/spm_unigram_fr.txt
   data: /Users/vireshkoli/Documents/MTech/Machine_Learning/ML_Project/datasets/cvss/cvss-c/fr-en/tgt_unigram6000
   loss_weight: 4.0
   rdrop_alpha: 0.0
   decoder_args:
      decoder_layers: 0
      decoder_embed_dim: 512
      decoder_ffn_embed_dim: 2048
      decoder_attention_heads: 8
   label_smoothing: 0.1